//! Tauri command surface.
//!
//! Every command is a thin shim over a `postcrate_core::Service`
//! method. Errors flow through `IpcError`. Commands are collected
//! into a single `tauri_specta::Builder` so the frontend gets a
//! generated `src/lib/bridge/bindings.ts` with typed `commands.*` calls.

pub mod actions;
pub mod audit;
pub mod bounces;
pub mod chaos;
pub mod emails;
pub mod forwarding;
pub mod mailboxes;
pub mod matcher;
pub mod recordings;
pub mod rendering;
pub mod scenarios;
pub mod server;
pub mod settings;
pub mod webhooks;

use tauri_specta::Builder;

/// Build the tauri-specta `Builder` with every command + event
/// registered. Shared by `lib.rs::run` (for the live invoke handler)
/// and `tests::export_bindings` (for the TypeScript generator).
pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
        // server
        server::server_status,
        server::boot_status,
        // mailboxes
        mailboxes::list_mailboxes,
        mailboxes::get_mailbox,
        mailboxes::create_mailbox,
        mailboxes::update_mailbox,
        mailboxes::delete_mailbox,
        mailboxes::start_mailbox,
        mailboxes::stop_mailbox,
        mailboxes::create_ephemeral,
        // emails
        emails::list_emails,
        emails::get_email,
        emails::get_email_raw,
        emails::get_email_smtp_transcript,
        emails::delete_email,
        emails::mark_read,
        emails::set_pinned,
        emails::set_starred,
        emails::set_note,
        emails::set_tag,
        emails::clear_mailbox,
        emails::purge_mailbox,
        emails::search_emails,
        // actions
        actions::release_email,
        actions::replay_email,
        // matcher
        matcher::wait_for_email,
        matcher::assert_email_matches,
        // chaos
        chaos::get_chaos,
        chaos::set_chaos,
        // bounces
        bounces::list_bounce_rules,
        bounces::upsert_bounce_rule,
        bounces::delete_bounce_rule,
        // settings
        settings::get_settings,
        settings::update_network_settings,
        settings::update_agent_settings,
        settings::update_inbox_settings,
        settings::update_advanced_settings,
        // audit
        audit::list_audit,
        audit::clear_audit,
        // webhooks
        webhooks::list_webhooks,
        webhooks::create_webhook,
        webhooks::delete_webhook,
        // forwarding
        forwarding::list_forwarding_rules,
        forwarding::create_forwarding_rule,
        forwarding::delete_forwarding_rule,
        // recordings
        recordings::export_recording,
        recordings::replay_recording,
        // per-email analysis
        scenarios::spam_report,
        scenarios::link_report,
        scenarios::auth_report,
        scenarios::unsub_report,
        // per-email rendering
        rendering::render_message,
        rendering::lint_message,
        rendering::a11y_message,
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Emits `src/lib/bridge/bindings.ts` so the frontend has typed
    /// `commands.*` symbols.
    #[test]
    fn export_bindings() {
        use specta_typescript::{BigIntExportBehavior, Typescript};
        specta_builder()
            .export(
                Typescript::default()
                    .bigint(BigIntExportBehavior::Number)
                    .header(
                        "// @ts-nocheck\n// @generated by tauri-specta — do not edit. Run the export_bindings test.\n",
                    ),
                "../src/lib/bridge/bindings.ts",
            )
            .expect("failed to export bindings");
    }
}
