// @ts-nocheck
// @generated by tauri-specta — do not edit. Run the export_bindings test.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async serverStatus() : Promise<Result<ServerStatus, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("server_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bootStatus() : Promise<Result<BootStatus, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("boot_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMailboxes(projectId: string | null) : Promise<Result<Mailbox[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mailboxes", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMailbox(id: string) : Promise<Result<Mailbox, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mailbox", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createMailbox(input: CreateMailboxInput) : Promise<Result<Mailbox, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_mailbox", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMailbox(id: string, patch: UpdateMailboxInput) : Promise<Result<Mailbox, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_mailbox", { id, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMailbox(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_mailbox", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Bring a stopped or failed mailbox's SMTP listener online and clear
 * the persistent `paused` intent. Errors propagate so the UI can show
 * why a bind failed (port in use, etc.) and revert its optimistic
 * status change.
 */
async startMailbox(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_mailbox", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tear down a mailbox's SMTP listener and remember the user intent
 * so the listener stays down across app restarts.
 */
async stopMailbox(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_mailbox", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createEphemeral(input: CreateEphemeralInput) : Promise<Result<EphemeralHandle, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_ephemeral", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEmails(mailboxId: string, limit: number, offset: number) : Promise<Result<EmailSummary[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_emails", { mailboxId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEmail(id: string) : Promise<Result<EmailDetail, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_email", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the raw RFC 5322 bytes of an email as a UTF-8 string.
 * 
 * We lossy-convert because the webview boundary is UTF-8; non-UTF-8
 * byte sequences (rare in legit mail) get the U+FFFD replacement
 * character. Binary parts are still served via `attachment://` for
 * byte-fidelity.
 */
async getEmailRaw(id: string) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_email_raw", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load the SMTP transcript captured at ingest time, if the
 * `Preserve SMTP transcript` pref was on when this email was
 * received. Returns `None` when the sidecar isn't on disk — the UI
 * uses that to hide the Transcript tab.
 */
async getEmailSmtpTranscript(id: string) : Promise<Result<string | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_email_smtp_transcript", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteEmail(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_email", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markRead(id: string, read: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_read", { id, read }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPinned(id: string, pinned: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_pinned", { id, pinned }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setStarred(id: string, starred: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_starred", { id, starred }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setNote(id: string, note: string | null) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_note", { id, note }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTag(id: string, tag: string | null) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tag", { id, tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearMailbox(mailboxId: string) : Promise<Result<number, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_mailbox", { mailboxId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async purgeMailbox(mailboxId: string) : Promise<Result<number, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_mailbox", { mailboxId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchEmails(q: string, mailboxId: string | null, limit: number) : Promise<Result<EmailSummary[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_emails", { q, mailboxId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async releaseEmail(id: string, to: string, relay: RelayConfig) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("release_email", { id, to, relay }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async replayEmail(id: string, targetMailboxId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replay_email", { id, targetMailboxId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async waitForEmail(predicate: EmailPredicate, timeoutSeconds: number) : Promise<Result<WaitOutcome, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wait_for_email", { predicate, timeoutSeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async assertEmailMatches(id: string, predicate: EmailPredicate) : Promise<Result<MatchResult, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("assert_email_matches", { id, predicate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChaos(mailboxId: string) : Promise<Result<ChaosConfig, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chaos", { mailboxId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setChaos(mailboxId: string, cfg: ChaosConfig) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_chaos", { mailboxId, cfg }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBounceRules(mailboxId: string) : Promise<Result<BounceRule[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_bounce_rules", { mailboxId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertBounceRule(rule: BounceRule) : Promise<Result<BounceRule, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_bounce_rule", { rule }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteBounceRule(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_bounce_rule", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<BackendSettings, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateNetworkSettings(prefs: NetworkPrefs) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_network_settings", { prefs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAgentSettings(prefs: AgentPrefs) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_agent_settings", { prefs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateInboxSettings(prefs: InboxPrefs) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_inbox_settings", { prefs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAdvancedSettings(prefs: AdvancedPrefs) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_advanced_settings", { prefs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAudit(limit: number, offset: number) : Promise<Result<AuditEntry[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_audit", { limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAudit(olderThanDays: number | null) : Promise<Result<number, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_audit", { olderThanDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWebhooks() : Promise<Result<Webhook[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_webhooks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWebhook(input: CreateWebhook) : Promise<Result<Webhook, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_webhook", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteWebhook(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_webhook", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listForwardingRules() : Promise<Result<ForwardingRule[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_forwarding_rules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createForwardingRule(input: CreateForwardingRule) : Promise<Result<ForwardingRule, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_forwarding_rule", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteForwardingRule(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_forwarding_rule", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportRecording(mailboxId: string, label: string | null) : Promise<Result<Recording, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_recording", { mailboxId, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async replayRecording(mailboxId: string, recording: Recording) : Promise<Result<number, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replay_recording", { mailboxId, recording }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async spamReport(id: string) : Promise<Result<SpamReport, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spam_report", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async linkReport(id: string) : Promise<Result<LinkReport, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("link_report", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authReport(id: string) : Promise<Result<AuthReport, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_report", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unsubReport(id: string) : Promise<Result<UnsubReport, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unsub_report", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderMessage(id: string, profile: Profile) : Promise<Result<RenderedPreview, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_message", { id, profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async lintMessage(id: string) : Promise<Result<LintReport, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lint_message", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async a11yMessage(id: string) : Promise<Result<A11yReport, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("a11y_message", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type A11yFinding = { rule: string; severity: string; message: string }
export type A11yReport = { findings: A11yFinding[] }
export type AdvancedPrefs = { debugLogging: boolean; preserveSmtpTranscript: boolean; auditRetainDays: number }
export type AgentPrefs = { defaultWaitTimeoutSeconds: number; logAgentRequests: boolean; confirmDestructiveActions: boolean }
export type AttachmentMeta = { id: string; filename: string | null; contentType: string | null; contentId: string | null; sizeBytes: number }
export type AuditEntry = { id: number; at: number; actor: string; action: string; targetKind: string | null; targetId: string | null; metadata: JsonValue | null }
export type AuthReport = { spf: AuthVerdict; dkim: AuthVerdict; dmarc: AuthVerdict; 
/**
 * True iff a `DKIM-Signature` header is present (regardless of
 * whether `Authentication-Results` confirmed it).
 */
hasDkimSignature: boolean; 
/**
 * What we found in `Authentication-Results`, if anything.
 */
authenticationResults: string | null }
export type AuthVerdict = "pass" | "fail" | "softfail" | "neutral" | "none" | 
/**
 * We don't know — neither `Authentication-Results` nor
 * per-protocol header gave us a verdict.
 */
"unknown"
export type BackendSettings = { network: NetworkPrefs; agents: AgentPrefs; inbox: InboxPrefs; advanced: AdvancedPrefs }
export type BootStatus = { kind: "starting" } | { kind: "ready" } | 
/**
 * Service failed to start. The reason is surfaced in the inbox
 * banner; the user fixes it in Preferences → Network and calls
 * `restart_service`.
 */
{ kind: "degraded"; reason: string }
export type BounceKind = "hard" | "soft"
export type BounceRule = { id?: string; mailboxId: string; addressPattern: string; bounceKind: BounceKind; smtpCode: number; smtpMessage: string; enabled?: boolean; createdAt?: number }
export type ChaosConfig = { enabled?: boolean; reject4XxProb?: number; reject5XxProb?: number; delayMsMin?: number; delayMsMax?: number; dropDuringDataProb?: number; malformedRespProb?: number; seed?: number | null }
export type CreateEphemeralInput = { projectId: string; name: string | null; ttlSeconds: number }
export type CreateForwardingRule = { mailboxId: string | null; targetAddresses: string[]; relay: RelayConfig; enabled: boolean | null }
export type CreateMailboxInput = { projectId: string; name: string; kind: MailboxKind; port: number | null; ttlSeconds: number | null; implicitTls?: boolean }
export type CreateWebhook = { mailboxId: string | null; url: string; authHeader: string | null; enabled: boolean | null }
export type DetectedLink = { url: string; kind: LinkKind; 
/**
 * Surface in the UI as a small warning chip.
 */
warnings: string[] }
export type EmailDetail = { id: string; mailboxId: string; receivedAt: number; from: string; to: string[]; subject: string | null; hasHtml: boolean; hasText: boolean; sizeBytes: number; read: boolean; pinned: boolean; starred: boolean; note: string | null; tag: string | null; headers: JsonValue; textBody: string | null; htmlBody: string | null; attachments: AttachmentMeta[]; messageId: string | null; inReplyTo: string | null; extSmtputf8: boolean; ext8Bitmime: boolean }
export type EmailPredicate = { 
/**
 * Restrict to a single mailbox.
 */
mailboxId: string | null; 
/**
 * Sender substring (case-insensitive).
 */
from: string | null; 
/**
 * Sender regex.
 */
fromRegex: string | null; 
/**
 * Any recipient contains this substring (case-insensitive).
 */
to: string | null; 
/**
 * Subject substring (case-insensitive).
 */
subject: string | null; 
/**
 * Subject regex.
 */
subjectRegex: string | null; 
/**
 * Plain-text body substring.
 */
bodyContains: string | null; 
/**
 * Plain-text body regex.
 */
bodyRegex: string | null; 
/**
 * `Some(true)` requires at least one attachment; `Some(false)`
 * requires zero. `None` means "don't care".
 */
hasAttachment: boolean | null; 
/**
 * Per-header predicates (any combination of substring/regex).
 */
headers?: HeaderPredicate[] }
export type EmailSummary = { id: string; mailboxId: string; receivedAt: number; from: string; to: string[]; subject: string | null; hasHtml: boolean; hasText: boolean; sizeBytes: number; read: boolean; pinned: boolean; starred: boolean; tag: string | null }
export type EphemeralHandle = { id: string; host: string; port: number; expiresAt: number }
export type Fidelity = "high" | "approximate" | "experimental"
export type ForwardingRule = { id: string; 
/**
 * `None` means "forward emails from every mailbox".
 */
mailboxId: string | null; targetAddresses: string[]; relay: RelayConfig; enabled: boolean; createdAt: number }
export type HeaderPredicate = { name: string; 
/**
 * Match the header value via case-insensitive substring.
 */
contains: string | null; 
/**
 * Match the header value via regex.
 */
regex: string | null }
export type InboxPrefs = { maxRetainedEmails: number; autoClearAfterDays: number; threadRelated: boolean; autoTag: boolean }
export type IpcError = { 
/**
 * Machine-readable code from `postcrate_core::Error::code()`
 * (e.g. `"port_in_use"`, `"mailbox_not_found"`, `"invalid"`).
 */
code: string; 
/**
 * Human-readable message suitable for surfacing to the user.
 */
message: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }
export type LinkCounts = { total: number; insecureHttp: number; mailto: number; tel: number; trackingLikely: number }
export type LinkKind = "http" | "https" | "mailto" | "tel" | "other"
export type LinkReport = { links: DetectedLink[]; counts: LinkCounts }
export type LintReport = { warnings: LintWarning[] }
export type LintWarning = { rule: string; 
/**
 * "high" / "medium" / "low".
 */
severity: string; message: string; 
/**
 * Where in the HTML we hit it — UI can highlight.
 */
byteOffset: number | null; 
/**
 * Which clients are affected by this issue.
 */
affects: string[] }
/**
 * A mailbox row joined with its current message count.
 */
export type Mailbox = { id: string; projectId: string; name: string; port: number; kind: MailboxKind; ttlSeconds: number | null; expiresAt: number | null; failed: boolean; failReason: string | null; createdAt: number; count: number; 
/**
 * When true, the listener for this mailbox wraps every accepted
 * socket in rustls *before* the SMTP banner (RFC 8314 §3.3,
 * port-465 style). Requires `--features tls`.
 */
implicitTls: boolean; 
/**
 * User-stopped (not failed): the mailbox exists but its listener
 * is intentionally not bound. Survives app restarts so Stop sticks.
 */
paused: boolean }
export type MailboxKind = "primary" | "shared" | "ephemeral"
export type MatchResult = { matched: boolean; mismatches: string[] }
export type NetworkPrefs = { smtpPort: number; httpApiPort: number; mcpEnabled: boolean; mcpPort: number; exposeOnLan: boolean; 
/**
 * Serve the HTTP API over HTTPS, reusing the cert/key configured
 * for STARTTLS. Requires `--features tls` and a valid cert.
 */
apiTls?: boolean; 
/**
 * When set, every `/api/v1/...` request must carry
 * `Authorization: Bearer <token>`. The healthz endpoint is
 * always open so liveness probes still work.
 */
apiAuthToken?: string | null }
export type Profile = "gmail_web" | "gmail_ios" | "outlook_desktop" | "outlook_web" | "apple_mail_mac" | "apple_mail_ios" | "yahoo_mail"
export type RecordedEnvelope = { mailFrom: string; rcptTo: string[]; receivedAt: number; extSmtputf8: boolean; ext8Bitmime: boolean; 
/**
 * Recorded for diagnostics; not used by replay (subject is in `raw`).
 */
subject: string | null }
export type RecordedMessage = { envelope: RecordedEnvelope; 
/**
 * Base64-encoded RFC 5322 bytes (what the SMTP DATA phase
 * produced before parsing). Storing raw keeps replay 1:1.
 */
rawB64: string }
export type Recording = { version: number; exportedAt: number; 
/**
 * Optional human-readable label so a user can tell two files apart.
 */
label?: string | null; messages: RecordedMessage[] }
export type RelayConfig = { 
/**
 * Relay host, e.g. `smtp.resend.com` or `127.0.0.1`.
 */
host: string; 
/**
 * Relay port. 25 for legacy, 587 for submission, 1025 for local.
 */
port: number; 
/**
 * Connect+IO timeout (defaults to 30s).
 */
timeoutSeconds?: number | null; 
/**
 * Glob-pattern allowlist of recipient addresses the relay is
 * allowed to deliver to. `["alice@example.com", "*@test.local"]`.
 * `None` or empty means "any recipient" (no restriction). Used
 * by `Service::release_email` to prevent accidentally pointing
 * the relay at production recipients.
 */
allowedRecipients?: string[] | null }
export type RenderedPreview = { profile: Profile; fidelity: Fidelity; html: string; 
/**
 * Notes about transforms that ran — useful for "why does it
 * look different here?" tooltips in the UI.
 */
applied: string[] }
export type ServerStatus = { runningMailboxes: number; httpRunning: boolean; errors: string[] }
export type SpamFactor = { rule: string; score: number; detail: string }
export type SpamReport = { score: number; verdict: SpamVerdict; factors: SpamFactor[] }
export type SpamVerdict = 
/**
 * Score < 2.0.
 */
"clean" | 
/**
 * 2.0 ≤ score < 5.0.
 */
"suspicious" | 
/**
 * Score ≥ 5.0.
 */
"likelyspam"
export type UnsubFinding = { rule: string; severity: string; message: string }
export type UnsubReport = { present: boolean; valid: boolean; uris: UnsubUri[]; oneClick: boolean; findings: UnsubFinding[] }
export type UnsubUri = { raw: string; scheme: string }
export type UpdateMailboxInput = { name: string | null; port: number | null; ttlSeconds: number | null }
export type WaitOutcome = { 
/**
 * The first email that satisfied the predicate, or `None` if we
 * timed out without a match.
 */
matched: EmailDetail | null; 
/**
 * Every captured email observed during the wait window (whether
 * or not it matched). Lets agents diagnose "code didn't try" vs
 * "code addressed it wrong".
 */
seenDuringWait: EmailSummary[] }
export type Webhook = { id: string; 
/**
 * `None` means this is a global webhook (fires for every mailbox).
 */
mailboxId: string | null; url: string; 
/**
 * Sent as the `Authorization` header verbatim. Use this for
 * `Bearer <token>` or basic-auth strings.
 */
authHeader: string | null; enabled: boolean; createdAt: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
